# Site settings
title: "Kalpesh Adhatrao"
description: "Graduate Student at the University of Southern California pursuing MS in Computer Science(Data Science)"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kalpesh Adhatrao"
resume_title:                   "Graduate Student at USC"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kalpesh.adhatrao@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "213-322-9429"
resume_contact_address:         "1226 W Adams Blvd. Apt. 3C, Los Angles, CA"

resume_header_contact_info:     "1226 W Adams Blvd. Apt. 3C, Los Angles, CA • 213-322-9429 • kalpesh.adhatrao@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>Hi there! This is Kalpesh Adhatrao. I am a Graduate Student pursuing MS in Computer Science(Data Science) at the University of Southern California. Before joining USC, I worked as a Senior Software Engineer for a US-Based client named Health Fidelity with the focus on delievering NLP and Analytics solutions to the Health Care system.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kelsadita/"
  resume_bitbucket_url:         "https://bitbucket.org/kelsadita/"
  resume_twitter_url:           "https://twitter.com/kelsadita"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kalpeshadhatrao/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://kelsadita.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
